### ISSUE TITLE
Remember last tab selection

### ISSUE THREAD

**Issue by bbhtt** [mtverlee/NextDNSManager#2] opened 2021-09-27 13:40 UTC
It'd be nice if the application remembered the last tab I was on before closing it (for example "Logs") rather then resetting back to the initial "Setup" tab.

**Comment by mtverlee** [comment] 2023-05-14 08:15
Closing this as it is a duplicate of [#4](https://github.com/mtverlee/NextDNSManager/issues/4).

**Closed** 2023-05-14 08:15 UTC
Labels: enhancement
